spring.application.name=notification
server.port=8084


spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=notification-group
kafka.topic.transaction-events=${KAFKA_TOPIC_TRANSACTION_EVENTS:transaction.events}

management.endpoints.web.exposure.include=health